[DEFAULT]
# Usa nftables como backend
banaction = nftables-multiport
backend = systemd
findtime = 600
bantime = -1
maxretry = 5

[sshd]
enabled = true
port    = 22
filter  = sshd
logpath = /var/log/auth.log
